FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/uberjar/todo-clojure-luminus.jar /todo-clojure-luminus/app.jar

EXPOSE 3000

CMD ["java", "-jar", "/todo-clojure-luminus/app.jar"]
